import styles from'@/styles/Layout.module.css';
import Head from 'next/head';
import { ChildProp } from '@/lib/props';
import { useRouter } from 'next/router';

export default function Layout({ children }: ChildProp) {
  const { asPath } = useRouter();

  return (
    <>
      <Head>
        <title>Links TypeORM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.main} ${asPath === '/' ? styles.image : ''}`}>
        {children}
      </div>
    </>
  )
}
